### ISSUE TITLE
README.md for check_vpn ?

### ISSUE THREAD

**Issue by 2Belette** [danfruehauf/nagios-plugins#18]
Hi, thanks first for this module!
When I followed the test you provide here : 
`
./check_vpn -t openvpn -H openvpn.vpn.com -u dan -p password -- --ca /etc/openvpn/ca.crt --config /etc/openvpn/vpn.com.conf --proto tcp`

I was not able to connect, adding -d tun to the command above and it is working.
I thought it was the default but apparently when -d tun is missing the script is not working correctly.

**Comment by danfruehauf** [comment]
@2Belette That depends on what you have in `/etc/openvpn/vpn.com.conf`. Can you please paste it here? (after removing sensitive information)

**Comment by 2Belette** [comment]
in my vpn.conf I got
dev-type tun
this is the reason why I don't understand

**Comment by danfruehauf** [comment]
If you are not willing to expose your vpn.conf file, a good way to start would be to print the following command:
https://github.com/danfruehauf/nagios-plugins/blob/master/check_vpn/check_vpn_plugins/openvpn.sh#L91

It'll give you a good understand of what's being run and you could probably isolate the problem quite easily.

**Comment by 2Belette** [comment]
here we go:
```

client

dev tun

proto tcp

mssfix 1300

remote xxxxx 1194

route-delay 2

nobind

auth-user-pass

verb 3

verify-x509-name xxxxx name

<ca>

-----BEGIN CERTIFICATE-----

xxxxxx

-----END CERTIFICATE-----

</ca>
```

**Comment by danfruehauf** [comment]
I reckon I've found the problem. I assumed `-d DEVICE` to always be present. Thing is in your case it wasn't. `check_vpn` needs it for device allocation and routing decisions. So best is to add `-d tun` in your command line.

In addition, I've added a fix to auto select `tun` in case it is not present.

**Comment by 2Belette** [comment]
yep many thanks! I figured out it quickly as you can see on my first comment but will be useful for others

**Comment by danfruehauf** [comment]
Awesome, and fixed for the next time as well!
